### ISSUE TITLE
not parsing subdirs of ignored directories

### ISSUE THREAD

**Issue by mdolling-gfz** [bitranox/igittigitt#10]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [x] support request

If behavior is intended, I need support, if not, it might be a bug

* **What is the current behavior?**

Currently files in subdirectories of ignored directories are not matched.

rule in `.gitignore`: `src_old/`
file **not** matched: `src_old/foo/bar.py`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

.gitignore
```
src_old/
.idea/
```

code
```
import igittigitt
import pprint
import pathlib

current_path = pathlib.Path(__file__).parent.absolute()

gitignore_parser = igittigitt.IgnoreParser()
gitignore_parser.parse_rule_files(current_path)

pp = pprint.PrettyPrinter(indent=4)
pp.pprint(gitignore_parser.rules)

print(gitignore_parser.match(pathlib.Path(f'{current_path}/src_old')))
print(gitignore_parser.match(pathlib.Path(f'{current_path}/src_old/foo.py')))
print(gitignore_parser.match(pathlib.Path(f'{current_path}/src_old/foo')))
print(gitignore_parser.match(pathlib.Path(f'{current_path}/src_old/foo/bar.py')))
```

output
```
[   IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/**/.idea', pattern_original='.idea/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=2),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/**/.idea/*', pattern_original='.idea/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=2),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/**/src_old', pattern_original='src_old/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=1),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/**/src_old/*', pattern_original='src_old/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=1),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/.idea', pattern_original='.idea/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=2),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/.idea/*', pattern_original='.idea/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=2),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/src_old', pattern_original='src_old/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=1),
    IgnoreRule(pattern_fnmatch='/home/md/PycharmProjects/test/src_old/*', pattern_original='src_old/', is_negation_rule=False, source_file=PosixPath('/home/md/PycharmProjects/test/.gitignore'), source_line_number=1)]
True
True
True
False
```

* **What is the expected behavior?**

Every subdir and file in subdirs of a ignored dir should be matched.

* **What is the motivation / use case for changing the behavior?**

in 1.0.6 it was matching all sub* of a ignored directory

* **Please tell us about your environment:**

- Release Number of the Repository used : 2.0.0
- Python Version :  3,8.5
- OS, OS Version :  Linux gfz 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)

**Comment by bitranox** [comment]
thanks for the report - I will look into it.

**Comment by bitranox** [comment]
I just released a new version which should correct the bug.
Please let me know if You find more issues !

**Comment by bitranox** [comment]
oops, just discovered that it was still not correctly working after adding some more tests.
From version 2.0.2 it should work, will release it just now.
Robert
