### ISSUE TITLE
Use glob.glob instead of Pathlib.glob to follow symlink

### ISSUE THREAD

**Issue by frthjf** [bitranox/igittigitt#16]
* **I'm submitting a ... **
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**

`parse_rule_files` relies on Pathlib's glob method that is [affected by a bug](https://bugs.python.org/issue33428) that prevents it from following symlinks. As a result, `.gitignore` files under symlinked directories are ignored.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Place a .gitigore file in a symlinked directory and use `parse_rule_files` on the parent folder. 

* **What is the expected behavior?**

Following [this solution](https://stackoverflow.com/questions/46529760/getting-glob-to-follow-symlinks-in-python), it would be best to rely on `glob.glob` that follows symlinks correctly.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Release Number of the Repository used : 2.0.3
- Python Version : 3.6.3
- OS, OS Version : MacOS

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)

https://stackoverflow.com/questions/46529760/getting-glob-to-follow-symlinks-in-python

Proposed solution:
```
rule_files = sorted(list(
                        glob(
                            f"{os.path.abspath(base_dir)}/**/.gitignore", recursive=True
                        )
                    )
                )
```

**Comment by bitranox** [comment]
Interesting - I will write some tests and look into it.

**Comment by bitranox** [comment]
it is done ... 

https://github.com/bitranox/igittigitt/releases/tag/v2.0.4

**Comment by frthjf** [comment]
Awesome, thank you!

**Comment by bitranox** [comment]
but please test it - Version 2.0.4 is passing the old tests, but I did not put additional tests for symlinked directories and files.
In case of any issues let me know.
