### ISSUE TITLE
Doesn't correctly handle base directories with a symlink in their components

### ISSUE THREAD

**Issue by jwodder** [bitranox/igittigitt#28]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Currently, if the base directory provided to an `IgnoreParser` method is a symlink or a descendant of a symlink, the parser will not match any files provided to it.

MVCE:

```python
#!/usr/bin/env python3
from pathlib import Path
from igittigitt import IgnoreParser

dir01 = Path("/tmp/igittigitt01")
dir01.mkdir()
dir02 = Path("/tmp/igittigitt02")
dir02.symlink_to(dir01)
(dir02 / "file.txt").touch()

parser = IgnoreParser()
parser.add_rule("*.txt", dir02)
print(parser.match(dir02 / "file.txt"))  # This prints "False", but it should print "True"
```

* **What is the expected behavior?**

A rule added for a directory path `p` should be honored for any filepath that starts with `p`.

* **What is the motivation / use case for changing the behavior?**

A rule added for a directory path `p` should be honored for any filepath that starts with `p`.

* **Please tell us about your environment:**

- Release Number of the Repository used : 2.1.0
- Python Version : 3.9.13
- OS, OS Version : Debian 11 (bullseye)

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)

I believe this bug is due to the use of the `pathlib.Path.resolve()` method, which resolves symlinks.

**Comment by bitranox** [comment]
thanks for the report - it will take a while, since I need to redesign the whole thing ...

**Comment by bitranox** [comment]
are You sure it is a bug ? 

see: https://git-scm.com/docs/gitignore#_pattern_format

The pattern foo/ will match a directory foo and paths underneath it, but will not match a regular file or a symbolic link foo (this is consistent with the way how pathspec works in general in Git)

Please let me know, otherwise I will close that issue.

**Comment by jwodder** [comment]
The pattern in question is just `*.txt`, which should match any file under the base directory ending in "`.txt`".  The passage you've quoted is only about patterns ending in slashes and has no bearing on whether a file under a base directory that happens to be a symlink is matched.

**Comment by bitranox** [comment]
yes, thanks, You are right. I will check ...

**Comment by bitranox** [comment]
just released a new version, it wotks now as expected - thanks for the report !
