### ISSUE TITLE
Match ignore file with different base paths?

### ISSUE THREAD

**Issue by omid3098** [bitranox/igittigitt#30]
* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **Do you want to request a *feature* or report a *bug*?**
None

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Not a bug

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Release Number of the Repository used : v2.1.4
- Python Version : 3.10.11
- OS, OS Version : Windows 11

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)

I want to process all files and subdirectories in a given directory and match them with ignore file.
For example,
My project is located in: `D:\project`
The ignore file is located in `D:\project\.ignore` and contains `*.txt`
I am trying to pass a system wide file path or directory to check if they match or not. like c:\myfile.txt
All files and directories are not matched if the basepath is not the same.
Is it even possible to do something like this?

**Comment by bitranox** [comment]
this is perfectly possible - 
You can read your file `D:\project\.ignore` and add each rule line by line by function `add_rule` with a new `base_path`
